name:                tictactoe-freer
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/tictactoe#readme
license:             BSD3
author:              Tim Clough
maintainer:          tmclough98@example.com
copyright:           2018 Tim Clough
category:            Web
extra-source-files:
- README.md

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - EmptyCase
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeFamilies
  - TypeFamilyDependencies
  - TypeOperators

dependencies:
  - base >= 4.7 && < 5
  - brick
  - freer-simple
  - mtl
  - vector
  - text
  - vty
  - array
  - transformers
  - aeson
  - unordered-containers
  - containers
  - syb
  - template-haskell
  - parsec
  - servant-server
  - warp
  - wai

library:
  source-dirs: lib
  exposed-modules:
    - Tictactoe.Types
    - Tictactoe.Players

executables:
  tictactoe:
    source-dirs:      
    - src
    - lib
    main:             Main.hs
  tictactoe-electron:
    source-dirs:      
    - app
    - lib
    main:             Main.hs

tests:
  unit:
    source-dirs: tests
    main: Tests.hs
    dependencies:
    - QuickCheck
    - tictactoe
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - tasty-smallcheck
    - template-haskell
    - file-embed
    - lens

